name: Publish

on:
  release:
    types:
      - published

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file:
          - amount.json
          - ingredient.json
          - language.json
          - link.json
          - quantity.json
          - recipe.json
          - step.json
          - unit.json
    steps:
      - uses: bruceadams/get-release@main
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: yarn install
      - run: VERSION=${{ steps.release.outputs.tag_name }} yarn build
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: dist/${{ matrix.file }}
          asset_name: ${{ matrix.file }}
          asset_content_type: application/json
