name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: martinbeentjes/npm-get-version-action@master
        id: version
      - uses: dev-drprasad/delete-tag-and-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASES_GITHUB_TOKEN }}
        with:
          delete_release: true
          tag_name: ${{ steps.version.outputs.current-version}}
      - uses: dev-drprasad/delete-tag-and-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASES_GITHUB_TOKEN }}
        with:
          delete_release: true
          tag_name: latest
      - uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASES_GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.current-version}}
          release_name: ${{ steps.version.outputs.current-version}}
          draft: false
          prerelease: false
      - uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASES_GITHUB_TOKEN }}
        with:
          tag_name: latest
          release_name: latest
          draft: false
          prerelease: false
