name: Tests

on:
  - push

jobs:
  test:
    name: Test schema
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: yarn install
      - run: yarn build
      - run: yarn test
